name: daniel_the_manual_spaniel
on:
  schedule:
    - cron: '5 12 * * 1-5'  # 12:05 UTC, Monday to Friday
  workflow_dispatch:

jobs:
  daniel_the_manual_spaniel:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rake notify:expired
        env:
          REALLY_POST_TO_SLACK: 1
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
